version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv/app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/srv/app/public
      - ./docker/nginx/log:/var/log/nginx

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d

volumes:
  mysql:
    driver: "local"